package h.json;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import h.model.shared.khall.Curriculum;
import h.model.shared.khall.Part;

public class CurriculumCreate
{
  public static List<Curriculum> create3()
  {
    List<Curriculum> ret = new ArrayList<>();

    Curriculum a1W1 = new Curriculum();
    a1W1.setDate(newDate("2018-01-15"));
    a1W1.setPart(Part.S_RETURN_VISIT_VIDEO);
    a1W1.setTheme(null);
    a1W1.setSource(null);
    a1W1.setDurationMinutes(5);
    a1W1.setSort(10);
    ret.add(a1W1);

    return ret;
  }

  public static List<Curriculum> create()
  {
    List<Curriculum> ret = new ArrayList<>();

    Curriculum chW1 = new Curriculum();
    chW1.setDate(newDate("2018-03-05"));
    chW1.setPart(Part.CHAIRMAN);
    chW1.setTheme(null);
    chW1.setSource(null);
    chW1.setDurationMinutes(null);
    chW1.setSort(1);
    ret.add(chW1);
    Curriculum s1W1 = new Curriculum();
    s1W1.setDate(newDate("2018-03-05"));
    s1W1.setPart(Part.SONG_1);
    s1W1.setTheme(null);
    s1W1.setSource("76");
    s1W1.setDurationMinutes(5);
    s1W1.setSort(2);
    ret.add(s1W1);
    Curriculum trW1 = new Curriculum();
    trW1.setDate(newDate("2018-03-05"));
    trW1.setPart(Part.TREASURES);
    trW1.setTheme("“Whoever Wants to Become Great Among You Must Be Your Minister”");
    trW1.setSource(null);
    trW1.setDurationMinutes(10);
    trW1.setSort(2);
    ret.add(trW1);
    Curriculum diW1 = new Curriculum();
    diW1.setDate(newDate("2018-03-05"));
    diW1.setPart(Part.DIGGING);
    diW1.setTheme(null);
    diW1.setSource("MATTHEW 20-21");
    diW1.setDurationMinutes(8);
    diW1.setSort(5);
    ret.add(diW1);
    Curriculum brW1 = new Curriculum();
    brW1.setDate(newDate("2018-03-05"));
    brW1.setPart(Part.BIBLE_READING);
    brW1.setTheme(null);
    brW1.setSource(null);
    brW1.setDurationMinutes(4);
    brW1.setSort(6);
    ret.add(brW1);

    Curriculum a2W1 = new Curriculum();
    a2W1.setDate(newDate("2018-03-05"));
    a2W1.setPart(Part.F_RETURN_VISIT);
    a2W1.setTheme(null);
    a2W1.setSource(null);
    a2W1.setDurationMinutes(3);
    a2W1.setSort(9);
    ret.add(a2W1);
    Curriculum a3W1 = new Curriculum();
    a3W1.setDate(newDate("2018-03-05"));
    a3W1.setPart(Part.BIBLE_STUDY);
    a3W1.setTheme(null);
    a3W1.setSource(null);
    a3W1.setDurationMinutes(6);
    a3W1.setSort(10);
    ret.add(a3W1);
    Curriculum l1W1 = new Curriculum();
    l1W1.setDate(newDate("2018-03-05"));
    l1W1.setPart(Part.LIVING_1);
    l1W1.setTheme("Local Needs");
    l1W1.setSource(null);
    l1W1.setDurationMinutes(5);
    l1W1.setSort(12);
    ret.add(l1W1);
    Curriculum l2W1 = new Curriculum();
    l2W1.setDate(newDate("2018-03-05"));
    l2W1.setPart(Part.LIVING_2);
    l2W1.setTheme("Organizational Accomplishments");
    l2W1.setSource(null);
    l2W1.setDurationMinutes(10);
    l2W1.setSort(13);
    ret.add(l2W1);
    Curriculum cbW1 = new Curriculum();
    cbW1.setDate(newDate("2018-03-05"));
    cbW1.setPart(Part.C_BIBLE_STUDY);
    cbW1.setTheme(null);
    cbW1.setSource(null);
    cbW1.setDurationMinutes(30);
    cbW1.setSort(14);
    ret.add(cbW1);
    Curriculum s3W1 = new Curriculum();
    s3W1.setDate(newDate("2018-03-05"));
    s3W1.setPart(Part.SONG_3);
    s3W1.setTheme(null);
    s3W1.setSource("53");
    s3W1.setDurationMinutes(5);
    s3W1.setSort(17);
    ret.add(s3W1);

    Curriculum chW2 = new Curriculum();
    chW2.setDate(newDate("2018-03-12"));
    chW2.setPart(Part.CHAIRMAN);
    chW2.setTheme(null);
    chW2.setSource(null);
    chW2.setDurationMinutes(null);
    chW2.setSort(1);
    ret.add(chW2);
    Curriculum s1W2 = new Curriculum();
    s1W2.setDate(newDate("2018-03-12"));
    s1W2.setPart(Part.SONG_1);
    s1W2.setTheme(null);
    s1W2.setSource("30");
    s1W2.setDurationMinutes(5);
    s1W2.setSort(2);
    ret.add(s1W2);
    Curriculum trW2 = new Curriculum();
    trW2.setDate(newDate("2018-03-12"));
    trW2.setPart(Part.TREASURES);
    trW2.setTheme("“Obey the Two Greatest Commandments”");
    trW2.setSource(null);
    trW2.setDurationMinutes(10);
    trW2.setSort(2);
    ret.add(trW2);
    Curriculum diW2 = new Curriculum();
    diW2.setDate(newDate("2018-03-12"));
    diW2.setPart(Part.DIGGING);
    diW2.setTheme(null);
    diW2.setSource("MATTHEW 22-23");
    diW2.setDurationMinutes(8);
    diW2.setSort(5);
    ret.add(diW2);
    Curriculum brW2 = new Curriculum();
    brW2.setDate(newDate("2018-03-12"));
    brW2.setPart(Part.BIBLE_READING);
    brW2.setTheme(null);
    brW2.setSource(null);
    brW2.setDurationMinutes(4);
    brW2.setSort(6);
    ret.add(brW2);
    Curriculum a1W2 = new Curriculum();
    a1W2.setDate(newDate("2018-03-12"));
    a1W2.setPart(Part.INITIAL_CALL);
    a1W2.setTheme(null);
    a1W2.setSource(null);
    a1W2.setDurationMinutes(2);
    a1W2.setSort(8);
    ret.add(a1W2);

    Curriculum a3W2 = new Curriculum();
    a3W2.setDate(newDate("2018-03-12"));
    a3W2.setPart(Part.BIBLE_STUDY);
    a3W2.setTheme(null);
    a3W2.setSource(null);
    a3W2.setDurationMinutes(6);
    a3W2.setSort(10);
    ret.add(a3W2);
    Curriculum l1W2 = new Curriculum();
    l1W2.setDate(newDate("2018-03-12"));
    l1W2.setPart(Part.LIVING_1);
    l1W2.setTheme("“Love for God and Neighbor​—How to Cultivate It”");
    l1W2.setSource(null);
    l1W2.setDurationMinutes(15);
    l1W2.setSort(12);
    ret.add(l1W2);

    Curriculum cbW2 = new Curriculum();
    cbW2.setDate(newDate("2018-03-12"));
    cbW2.setPart(Part.C_BIBLE_STUDY);
    cbW2.setTheme(null);
    cbW2.setSource(null);
    cbW2.setDurationMinutes(30);
    cbW2.setSort(14);
    ret.add(cbW2);
    Curriculum s3W2 = new Curriculum();
    s3W2.setDate(newDate("2018-03-12"));
    s3W2.setPart(Part.SONG_3);
    s3W2.setTheme(null);
    s3W2.setSource("52");
    s3W2.setDurationMinutes(5);
    s3W2.setSort(17);
    ret.add(s3W2);

    Curriculum chW3 = new Curriculum();
    chW3.setDate(newDate("2018-03-19"));
    chW3.setPart(Part.CHAIRMAN);
    chW3.setTheme(null);
    chW3.setSource(null);
    chW3.setDurationMinutes(null);
    chW3.setSort(1);
    ret.add(chW3);
    Curriculum s1W3 = new Curriculum();
    s1W3.setDate(newDate("2018-03-19"));
    s1W3.setPart(Part.SONG_1);
    s1W3.setTheme(null);
    s1W3.setSource("126");
    s1W3.setDurationMinutes(5);
    s1W3.setSort(2);
    ret.add(s1W3);
    Curriculum trW3 = new Curriculum();
    trW3.setDate(newDate("2018-03-19"));
    trW3.setPart(Part.TREASURES);
    trW3.setTheme("“Remain Spiritually Awake During the Last Days”");
    trW3.setSource(null);
    trW3.setDurationMinutes(10);
    trW3.setSort(2);
    ret.add(trW3);
    Curriculum diW3 = new Curriculum();
    diW3.setDate(newDate("2018-03-19"));
    diW3.setPart(Part.DIGGING);
    diW3.setTheme(null);
    diW3.setSource("MATTHEW 24");
    diW3.setDurationMinutes(8);
    diW3.setSort(5);
    ret.add(diW3);
    Curriculum brW3 = new Curriculum();
    brW3.setDate(newDate("2018-03-19"));
    brW3.setPart(Part.BIBLE_READING);
    brW3.setTheme(null);
    brW3.setSource(null);
    brW3.setDurationMinutes(4);
    brW3.setSort(6);
    ret.add(brW3);
    Curriculum a1W3 = new Curriculum();
    a1W3.setDate(newDate("2018-03-19"));
    a1W3.setPart(Part.INITIAL_CALL);
    a1W3.setTheme(null);
    a1W3.setSource(null);
    a1W3.setDurationMinutes(2);
    a1W3.setSort(8);
    ret.add(a1W3);
    Curriculum a2W3 = new Curriculum();
    a2W3.setDate(newDate("2018-03-19"));
    a2W3.setPart(Part.F_RETURN_VISIT);
    a2W3.setTheme(null);
    a2W3.setSource(null);
    a2W3.setDurationMinutes(3);
    a2W3.setSort(9);
    ret.add(a2W3);

    Curriculum l1W3 = new Curriculum();
    l1W3.setDate(newDate("2018-03-19"));
    l1W3.setPart(Part.LIVING_1);
    l1W3.setTheme("“Close to the End of This System of Things”");
    l1W3.setSource(null);
    l1W3.setDurationMinutes(15);
    l1W3.setSort(12);
    ret.add(l1W3);

    Curriculum cbW3 = new Curriculum();
    cbW3.setDate(newDate("2018-03-19"));
    cbW3.setPart(Part.C_BIBLE_STUDY);
    cbW3.setTheme(null);
    cbW3.setSource(null);
    cbW3.setDurationMinutes(30);
    cbW3.setSort(14);
    ret.add(cbW3);
    Curriculum s3W3 = new Curriculum();
    s3W3.setDate(newDate("2018-03-19"));
    s3W3.setPart(Part.SONG_3);
    s3W3.setTheme(null);
    s3W3.setSource("97");
    s3W3.setDurationMinutes(5);
    s3W3.setSort(17);
    ret.add(s3W3);

    Curriculum chW4 = new Curriculum();
    chW4.setDate(newDate("2018-03-26"));
    chW4.setPart(Part.CHAIRMAN);
    chW4.setTheme(null);
    chW4.setSource(null);
    chW4.setDurationMinutes(null);
    chW4.setSort(1);
    ret.add(chW4);
    Curriculum s1W4 = new Curriculum();
    s1W4.setDate(newDate("2018-03-26"));
    s1W4.setPart(Part.SONG_1);
    s1W4.setTheme(null);
    s1W4.setSource("143");
    s1W4.setDurationMinutes(5);
    s1W4.setSort(2);
    ret.add(s1W4);
    Curriculum trW4 = new Curriculum();
    trW4.setDate(newDate("2018-03-26"));
    trW4.setPart(Part.TREASURES);
    trW4.setTheme("“Keep on the Watch”");
    trW4.setSource(null);
    trW4.setDurationMinutes(10);
    trW4.setSort(2);
    ret.add(trW4);
    Curriculum diW4 = new Curriculum();
    diW4.setDate(newDate("2018-03-26"));
    diW4.setPart(Part.DIGGING);
    diW4.setTheme(null);
    diW4.setSource("MATTHEW 25");
    diW4.setDurationMinutes(8);
    diW4.setSort(5);
    ret.add(diW4);
    Curriculum brW4 = new Curriculum();
    brW4.setDate(newDate("2018-03-26"));
    brW4.setPart(Part.BIBLE_READING);
    brW4.setTheme(null);
    brW4.setSource(null);
    brW4.setDurationMinutes(4);
    brW4.setSort(6);
    ret.add(brW4);
    Curriculum a1W4 = new Curriculum();
    a1W4.setDate(newDate("2018-03-26"));
    a1W4.setPart(Part.S_RETURN_VISIT);
    a1W4.setTheme(null);
    a1W4.setSource(null);
    a1W4.setDurationMinutes(3);
    a1W4.setSort(8);
    ret.add(a1W4);
    Curriculum a2W4 = new Curriculum();
    a2W4.setDate(newDate("2018-03-26"));
    a2W4.setPart(Part.T_RETURN_VISIT);
    a2W4.setTheme(null);
    a2W4.setSource(null);
    a2W4.setDurationMinutes(3);
    a2W4.setSort(9);
    ret.add(a2W4);
    Curriculum a3W4 = new Curriculum();
    a3W4.setDate(newDate("2018-03-26"));
    a3W4.setPart(Part.TALK);
    a3W4.setTheme(null);
    a3W4.setSource(null);
    a3W4.setDurationMinutes(6);
    a3W4.setSort(10);
    ret.add(a3W4);
    Curriculum l1W4 = new Curriculum();
    l1W4.setDate(newDate("2018-03-26"));
    l1W4.setPart(Part.LIVING_1);
    l1W4.setTheme("“Improving Our Skills in the Ministry​—Teaching Our Students to Prepare”");
    l1W4.setSource(null);
    l1W4.setDurationMinutes(10);
    l1W4.setSort(12);
    ret.add(l1W4);
    Curriculum l2W4 = new Curriculum();
    l2W4.setDate(newDate("2018-03-26"));
    l2W4.setPart(Part.LIVING_2);
    l2W4.setTheme("Welcome Our Guests");
    l2W4.setSource(null);
    l2W4.setDurationMinutes(5);
    l2W4.setSort(13);
    ret.add(l2W4);
    Curriculum cbW4 = new Curriculum();
    cbW4.setDate(newDate("2018-03-26"));
    cbW4.setPart(Part.C_BIBLE_STUDY);
    cbW4.setTheme(null);
    cbW4.setSource(null);
    cbW4.setDurationMinutes(30);
    cbW4.setSort(14);
    ret.add(cbW4);
    Curriculum s3W4 = new Curriculum();
    s3W4.setDate(newDate("2018-03-26"));
    s3W4.setPart(Part.SONG_3);
    s3W4.setTheme(null);
    s3W4.setSource("79");
    s3W4.setDurationMinutes(5);
    s3W4.setSort(17);
    ret.add(s3W4);

    return ret;
  }

  public static List<Curriculum> create2()
  {
    List<Curriculum> ret = new ArrayList<>();

    Curriculum chW1 = new Curriculum();
    chW1.setDate(newDate("2018-02-05"));
    chW1.setPart(Part.CHAIRMAN);
    chW1.setTheme(null);
    chW1.setSource(null);
    chW1.setDurationMinutes(null);
    chW1.setSort(1);
    ret.add(chW1);
    Curriculum s1W1 = new Curriculum();
    s1W1.setDate(newDate("2018-02-05"));
    s1W1.setPart(Part.SONG_1);
    s1W1.setTheme(null);
    s1W1.setSource("27");
    s1W1.setDurationMinutes(5);
    s1W1.setSort(2);
    ret.add(s1W1);
    Curriculum trW1 = new Curriculum();
    trW1.setDate(newDate("2018-02-05"));
    trW1.setPart(Part.TREASURES);
    trW1.setTheme("“The Illustration of the Wheat and the Weeds”");
    trW1.setSource(null);
    trW1.setDurationMinutes(10);
    trW1.setSort(2);
    ret.add(trW1);
    Curriculum diW1 = new Curriculum();
    diW1.setDate(newDate("2018-02-05"));
    diW1.setPart(Part.DIGGING);
    diW1.setTheme(null);
    diW1.setSource("MATTHEW 12-13");
    diW1.setDurationMinutes(8);
    diW1.setSort(5);
    ret.add(diW1);
    Curriculum brW1 = new Curriculum();
    brW1.setDate(newDate("2018-02-05"));
    brW1.setPart(Part.BIBLE_READING);
    brW1.setTheme(null);
    brW1.setSource(null);
    brW1.setDurationMinutes(4);
    brW1.setSort(6);
    ret.add(brW1);

    Curriculum a2W1 = new Curriculum();
    a2W1.setDate(newDate("2018-02-05"));
    a2W1.setPart(Part.F_RETURN_VISIT);
    a2W1.setTheme(null);
    a2W1.setSource(null);
    a2W1.setDurationMinutes(3);
    a2W1.setSort(9);
    ret.add(a2W1);
    Curriculum a3W1 = new Curriculum();
    a3W1.setDate(newDate("2018-02-05"));
    a3W1.setPart(Part.BIBLE_STUDY);
    a3W1.setTheme(null);
    a3W1.setSource(null);
    a3W1.setDurationMinutes(6);
    a3W1.setSort(10);
    ret.add(a3W1);
    Curriculum l1W1 = new Curriculum();
    l1W1.setDate(newDate("2018-02-05"));
    l1W1.setPart(Part.LIVING_1);
    l1W1.setTheme("Local Needs");
    l1W1.setSource(null);
    l1W1.setDurationMinutes(5);
    l1W1.setSort(12);
    ret.add(l1W1);
    Curriculum l2W1 = new Curriculum();
    l2W1.setDate(newDate("2018-02-05"));
    l2W1.setPart(Part.LIVING_2);
    l2W1.setTheme("“Kingdom Illustrations and Their Meaning for Us”");
    l2W1.setSource(null);
    l2W1.setDurationMinutes(10);
    l2W1.setSort(13);
    ret.add(l2W1);
    Curriculum cbW1 = new Curriculum();
    cbW1.setDate(newDate("2018-02-05"));
    cbW1.setPart(Part.C_BIBLE_STUDY);
    cbW1.setTheme(null);
    cbW1.setSource(null);
    cbW1.setDurationMinutes(30);
    cbW1.setSort(14);
    ret.add(cbW1);
    Curriculum s3W1 = new Curriculum();
    s3W1.setDate(newDate("2018-02-05"));
    s3W1.setPart(Part.SONG_3);
    s3W1.setTheme(null);
    s3W1.setSource("10");
    s3W1.setDurationMinutes(5);
    s3W1.setSort(17);
    ret.add(s3W1);

    Curriculum chW2 = new Curriculum();
    chW2.setDate(newDate("2018-02-12"));
    chW2.setPart(Part.CHAIRMAN);
    chW2.setTheme(null);
    chW2.setSource(null);
    chW2.setDurationMinutes(null);
    chW2.setSort(1);
    ret.add(chW2);
    Curriculum s1W2 = new Curriculum();
    s1W2.setDate(newDate("2018-02-12"));
    s1W2.setPart(Part.SONG_1);
    s1W2.setTheme(null);
    s1W2.setSource("93");
    s1W2.setDurationMinutes(5);
    s1W2.setSort(2);
    ret.add(s1W2);
    Curriculum trW2 = new Curriculum();
    trW2.setDate(newDate("2018-02-12"));
    trW2.setPart(Part.TREASURES);
    trW2.setTheme("“Feeding Many Through the Hands of a Few”");
    trW2.setSource(null);
    trW2.setDurationMinutes(10);
    trW2.setSort(2);
    ret.add(trW2);
    Curriculum diW2 = new Curriculum();
    diW2.setDate(newDate("2018-02-12"));
    diW2.setPart(Part.DIGGING);
    diW2.setTheme(null);
    diW2.setSource("MATTHEW 14-15");
    diW2.setDurationMinutes(8);
    diW2.setSort(5);
    ret.add(diW2);
    Curriculum brW2 = new Curriculum();
    brW2.setDate(newDate("2018-02-12"));
    brW2.setPart(Part.BIBLE_READING);
    brW2.setTheme(null);
    brW2.setSource(null);
    brW2.setDurationMinutes(4);
    brW2.setSort(6);
    ret.add(brW2);
    Curriculum a1W2 = new Curriculum();
    a1W2.setDate(newDate("2018-02-12"));
    a1W2.setPart(Part.INITIAL_CALL);
    a1W2.setTheme(null);
    a1W2.setSource(null);
    a1W2.setDurationMinutes(2);
    a1W2.setSort(8);
    ret.add(a1W2);

    Curriculum a3W2 = new Curriculum();
    a3W2.setDate(newDate("2018-02-12"));
    a3W2.setPart(Part.TALK);
    a3W2.setTheme(null);
    a3W2.setSource(null);
    a3W2.setDurationMinutes(6);
    a3W2.setSort(10);
    ret.add(a3W2);
    Curriculum l1W2 = new Curriculum();
    l1W2.setDate(newDate("2018-02-12"));
    l1W2.setPart(Part.LIVING_1);
    l1W2.setTheme("Become Jehovah’s Friend​—Making Friends");
    l1W2.setSource(null);
    l1W2.setDurationMinutes(7);
    l1W2.setSort(12);
    ret.add(l1W2);
    Curriculum l2W2 = new Curriculum();
    l2W2.setDate(newDate("2018-02-12"));
    l2W2.setPart(Part.LIVING_2);
    l2W2.setTheme("“Honor Your Father and Your Mother”");
    l2W2.setSource(null);
    l2W2.setDurationMinutes(8);
    l2W2.setSort(13);
    ret.add(l2W2);
    Curriculum cbW2 = new Curriculum();
    cbW2.setDate(newDate("2018-02-12"));
    cbW2.setPart(Part.C_BIBLE_STUDY);
    cbW2.setTheme(null);
    cbW2.setSource(null);
    cbW2.setDurationMinutes(30);
    cbW2.setSort(14);
    ret.add(cbW2);
    Curriculum s3W2 = new Curriculum();
    s3W2.setDate(newDate("2018-02-12"));
    s3W2.setPart(Part.SONG_3);
    s3W2.setTheme(null);
    s3W2.setSource("148");
    s3W2.setDurationMinutes(5);
    s3W2.setSort(17);
    ret.add(s3W2);

    Curriculum chW3 = new Curriculum();
    chW3.setDate(newDate("2018-02-19"));
    chW3.setPart(Part.CHAIRMAN);
    chW3.setTheme(null);
    chW3.setSource(null);
    chW3.setDurationMinutes(null);
    chW3.setSort(1);
    ret.add(chW3);
    Curriculum s1W3 = new Curriculum();
    s1W3.setDate(newDate("2018-02-19"));
    s1W3.setPart(Part.SONG_1);
    s1W3.setTheme(null);
    s1W3.setSource("45");
    s1W3.setDurationMinutes(5);
    s1W3.setSort(2);
    ret.add(s1W3);
    Curriculum trW3 = new Curriculum();
    trW3.setDate(newDate("2018-02-19"));
    trW3.setPart(Part.TREASURES);
    trW3.setTheme("“Whose Thoughts Are You Thinking?”");
    trW3.setSource(null);
    trW3.setDurationMinutes(10);
    trW3.setSort(2);
    ret.add(trW3);
    Curriculum diW3 = new Curriculum();
    diW3.setDate(newDate("2018-02-19"));
    diW3.setPart(Part.DIGGING);
    diW3.setTheme(null);
    diW3.setSource("MATTHEW 16-17");
    diW3.setDurationMinutes(8);
    diW3.setSort(5);
    ret.add(diW3);
    Curriculum brW3 = new Curriculum();
    brW3.setDate(newDate("2018-02-19"));
    brW3.setPart(Part.BIBLE_READING);
    brW3.setTheme(null);
    brW3.setSource(null);
    brW3.setDurationMinutes(4);
    brW3.setSort(6);
    ret.add(brW3);
    Curriculum a1W3 = new Curriculum();
    a1W3.setDate(newDate("2018-02-19"));
    a1W3.setPart(Part.INITIAL_CALL);
    a1W3.setTheme(null);
    a1W3.setSource(null);
    a1W3.setDurationMinutes(2);
    a1W3.setSort(8);
    ret.add(a1W3);
    Curriculum a2W3 = new Curriculum();
    a2W3.setDate(newDate("2018-02-19"));
    a2W3.setPart(Part.F_RETURN_VISIT);
    a2W3.setTheme(null);
    a2W3.setSource(null);
    a2W3.setDurationMinutes(3);
    a2W3.setSort(9);
    ret.add(a2W3);

    Curriculum l1W3 = new Curriculum();
    l1W3.setDate(newDate("2018-02-19"));
    l1W3.setPart(Part.LIVING_1);
    l1W3.setTheme("“Improving Our Skills in the Ministry​—Using Questions Effectively”");
    l1W3.setSource(null);
    l1W3.setDurationMinutes(15);
    l1W3.setSort(12);
    ret.add(l1W3);

    Curriculum cbW3 = new Curriculum();
    cbW3.setDate(newDate("2018-02-19"));
    cbW3.setPart(Part.C_BIBLE_STUDY);
    cbW3.setTheme(null);
    cbW3.setSource(null);
    cbW3.setDurationMinutes(30);
    cbW3.setSort(14);
    ret.add(cbW3);
    Curriculum s3W3 = new Curriculum();
    s3W3.setDate(newDate("2018-02-19"));
    s3W3.setPart(Part.SONG_3);
    s3W3.setTheme(null);
    s3W3.setSource("134");
    s3W3.setDurationMinutes(5);
    s3W3.setSort(17);
    ret.add(s3W3);

    Curriculum chW4 = new Curriculum();
    chW4.setDate(newDate("2018-02-26"));
    chW4.setPart(Part.CHAIRMAN);
    chW4.setTheme(null);
    chW4.setSource(null);
    chW4.setDurationMinutes(null);
    chW4.setSort(1);
    ret.add(chW4);
    Curriculum s1W4 = new Curriculum();
    s1W4.setDate(newDate("2018-02-26"));
    s1W4.setPart(Part.SONG_1);
    s1W4.setTheme(null);
    s1W4.setSource("121");
    s1W4.setDurationMinutes(5);
    s1W4.setSort(2);
    ret.add(s1W4);
    Curriculum trW4 = new Curriculum();
    trW4.setDate(newDate("2018-02-26"));
    trW4.setPart(Part.TREASURES);
    trW4.setTheme("“Carefully Avoid Stumbling Yourself and Others”");
    trW4.setSource(null);
    trW4.setDurationMinutes(10);
    trW4.setSort(2);
    ret.add(trW4);
    Curriculum diW4 = new Curriculum();
    diW4.setDate(newDate("2018-02-26"));
    diW4.setPart(Part.DIGGING);
    diW4.setTheme(null);
    diW4.setSource("MATTHEW 18-19");
    diW4.setDurationMinutes(8);
    diW4.setSort(5);
    ret.add(diW4);
    Curriculum brW4 = new Curriculum();
    brW4.setDate(newDate("2018-02-26"));
    brW4.setPart(Part.BIBLE_READING);
    brW4.setTheme(null);
    brW4.setSource(null);
    brW4.setDurationMinutes(4);
    brW4.setSort(6);
    ret.add(brW4);
    Curriculum a1W4 = new Curriculum();
    a1W4.setDate(newDate("2018-02-26"));
    a1W4.setPart(Part.S_RETURN_VISIT);
    a1W4.setTheme(null);
    a1W4.setSource(null);
    a1W4.setDurationMinutes(3);
    a1W4.setSort(8);
    ret.add(a1W4);
    Curriculum a2W4 = new Curriculum();
    a2W4.setDate(newDate("2018-02-26"));
    a2W4.setPart(Part.T_RETURN_VISIT);
    a2W4.setTheme(null);
    a2W4.setSource(null);
    a2W4.setDurationMinutes(3);
    a2W4.setSort(9);
    ret.add(a2W4);
    Curriculum a3W4 = new Curriculum();
    a3W4.setDate(newDate("2018-02-26"));
    a3W4.setPart(Part.BIBLE_STUDY);
    a3W4.setTheme(null);
    a3W4.setSource(null);
    a3W4.setDurationMinutes(6);
    a3W4.setSort(10);
    ret.add(a3W4);
    Curriculum l1W4 = new Curriculum();
    l1W4.setDate(newDate("2018-02-26"));
    l1W4.setPart(Part.LIVING_1);
    l1W4.setTheme("Never Be a Cause for Stumbling");
    l1W4.setSource(null);
    l1W4.setDurationMinutes(9);
    l1W4.setSort(12);
    ret.add(l1W4);
    Curriculum l2W4 = new Curriculum();
    l2W4.setDate(newDate("2018-02-26"));
    l2W4.setPart(Part.LIVING_2);
    l2W4.setTheme("Memorial Campaign to Begin March 3");
    l2W4.setSource(null);
    l2W4.setDurationMinutes(6);
    l2W4.setSort(13);
    ret.add(l2W4);
    Curriculum cbW4 = new Curriculum();
    cbW4.setDate(newDate("2018-02-26"));
    cbW4.setPart(Part.C_BIBLE_STUDY);
    cbW4.setTheme(null);
    cbW4.setSource(null);
    cbW4.setDurationMinutes(30);
    cbW4.setSort(14);
    ret.add(cbW4);
    Curriculum s3W4 = new Curriculum();
    s3W4.setDate(newDate("2018-02-26"));
    s3W4.setPart(Part.SONG_3);
    s3W4.setTheme(null);
    s3W4.setSource("133");
    s3W4.setDurationMinutes(5);
    s3W4.setSort(17);
    ret.add(s3W4);

    return ret;
  }

  private static Date newDate(String inText)
  {
    try
    {
      return new SimpleDateFormat("yyyy-MM-dd").parse(inText);
    }
    catch (ParseException e)
    {
      e.printStackTrace();
    }
    return null;
  }
}